# -*- coding: utf-8 -*-
"""CDIa6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJtLGGisQ7-8QUJThPqVj2dbtlUpnxAG
"""

pip install openai

import ast
import openai
import json

# Enter your OpenAI API key:
openai.api_key = 'xxxxxxxxxxxxxxxxx'

# This is a simple example of a generative agent using the prompt method.
# You should enhance it to create a functional agent.
# You can consider designing multiple agents:
# (For example, Agent_A for updating memory, Agent_B for receiving updated memory and providing user inferences)

def agent(pre_obs, new_obs):
    prompts = [
        {
            "role": "assistant",
            "content":
                "You are one of the agents for an AI research assistant, named assistant1, used for updating 'pre_obsevation', and your task is designed to help users by providing explanations of professional terms when needed during their literature reading.\n"
                "Your task is to update 'previous observation' using 'new observation'.\n"

                "\n"
                "'previous observation' has five fields:\n"
                "1. \"Reading part\": All individual records of what the user has read.\n"
                "2. \"Interaction\": All individual records of the user's interaction with the text.\n"
                "3. \"Time spent\": All individual records of time spent by the user reading.\n"
                "4. \"Agent action\": All individual records of actions and time taken by the agent.\n"
                "5. \"User feedback\": All individual records of user feedback to the AI.\n"
                "\n"
                "'new observation' is a sentence. You need to categorize them into the following four fields:\n"
                "1. \"Reading part\": You should extract the content of the document that the user is reading. It is just the part that comes before (the reading part above).\n"
                "2. \"Interaction\": The user's interaction with the text. You should extract the user's interaction with the document in this observation, such as highlighting annotations and searching for translations.\n"
                "3. \"Time spent\": The time spent by the user reading. You should extract the time spent by the user reading in this observation.\n"
                "4. \"User feedback\": Extract the content of the user feedback on the AI.\n"
                "\n"
                "This is your 'previous observation':\n"
                f"{pre_obs}\n"
                "\n"
                "This is your 'new observation':\n"
                f"{new_obs}\n"
                "\n"
                "This is how you update 'previous observation' by using 'new observation':\n"
                "1. \"Reading part\": Based on the previous record and add the corresponding part of 'new observation' after the record as an update.\n"
                "2. \"Interaction\": Based on the previous record and add the corresponding part of 'new observation' after the record as an update. Do not update if there is no interaction.\n"
                "3. \"Time spent\": Based on the previous record and add the corresponding part of 'new observation' aafter the record as an update.\n"
                "4. \"Agent action\": The content in this part is not observable in this 'new observation'. You need to wait until assistant3 completes the decision-making. After that, you should combine the fields 'Explanation' and 'Timing' from the generated 'action' by assistant3 into a short sentence description. Combine this with the 'Agent action' part from 'previous observation' to update the coherent record of 'Agent action'.\n"
                "5. \"User feedback\": Based on the previous record and add the corresponding part of 'new observation' after the record as an update. Do not update if there is no user feedback .\n"
                "\n"





                "You are another agent for an AI research assistant, named assistant2, used to infer user needs. Your task is designed to help users by providing inferences about user needs during their literature reading. You are designed to generate inferences for user demands.\n"
                "Your task is to generate an 'inference' based on the updated 'previous observation' generated by assistant1.\n"

                "\n"
                "This updated 'previous observation' generated by assistant1 and includes five fields\n"
                # "1. \"Reading part\": A coherent record of the content and section of the literature the user is reading in the current and past observations.\n"
                # "2. \"Interaction\": A coherent record of the user's interaction with the text in the current and past observations.\n"
                # "3. \"Time spent\": A coherent record of the time the user has spent on the content section in the current and past observations.\n"
                # "4. \"Agent action\": A coherent record of the agent's actions after the previous observation and all previous actions.\n"
                # "5. \"User feedback\": A coherent record of the user's feedback on the AI assistant's behavior after the previous observation and all previous feedback.\n"
                "\n"
                "You need to generate an 'inference'.\n"
                "\n"
                "This 'inference' includes three fields:\n"
                "1. \"Needs inferring\": The part of the content you infer the user needs an explanation for.\n"
                "2. \"Types of Needs\": The forms of relevant explanations you analyze the user needs.\n"
                "3. \"Personalization\": The user's feedback on the agent's behavior you analyze.\n"
                "\n"
                "This is how you generate 'inference' based on updated 'previous observation' generated by assistant1:\n"
                "1. \"Needs inferring\": You need to infer which part of the content the user needs an explanation for based on 'Reading part', 'Interaction', and 'Time spent' in 'now observation'. Rely on the user's reading position, interaction behavior, and the time spent to infer terms the user may find challenging to understand or terms of interest. (Which part the user needs an explanation for).\n"
                "2. \"Types of Needs\": You need to analyze the forms of relevant explanations the user needs based on 'Reading part', 'Interaction', 'Time spent', and the user's reading section. For example, if the user spends a long time in the methods section, you might provide a detailed explanation of the term in the context of the method. (What form of explanation the user needs).\n"
                "3. \"Personalization\": You need to analyze the user's suggestions for agent behavior based on 'Agent action', 'User feedback', and combine them to analyze what the user needs and what the user does not want.\n"
                "\n"






                "After assistant2 completes the task, it's assistant3's turn to perform the task."
                "\n"







                "You are another agent for an AI research assistant, named assistant3, used to decide what actions to take. Your task is designed to help users by providing professional term explanations during their literature reading. You are designed to decide on action decisions.\n"
                "Your task is to generate AI assistant's action decisions based on updated 'previous observation' generated by assistant1 and 'inference' generated by assistant2.\n"

                "\n"
                "This updated 'previous observation' generated by assistant1, and it includes five fields\n"
                # "1. \"Reading part\": A coherent record of the content and section of the literature the user is reading in the current and past observations.\n"
                # "2. \"Interaction\": A coherent record of the user's interaction with the text in the current and past observations.\n"
                # "3. \"Time spent\": A coherent record of the time the user has spent on the content section in the current and past observations.\n"
                # "4. \"Agent action\": A coherent record of the agent's actions after the previous observation and all previous actions.\n"
                # "5. \"User feedback\": A coherent record of the user's feedback on the AI assistant's behavior after the previous observation and all previous feedback.\n"
                "\n"
                "I will provide you with an 'inference'.\n"
                "\n"
                "This 'inference' is generated by assistant2 and includes three fields:\n"
                "1. \"Needs inferring\": The inferred part of the content the user needs an explanation for.\n"
                "2. \"Types of Needs\": The analyzed forms of relevant explanations the user needs.\n"
                "3. \"Personalization\": The analyzed user suggestions for agent behavior.\n"
                "\n"
                "You need to generate an 'action'.\n"
                "\n"
                "This 'action' includes two fields:\n"
                "1. \"Explanation\": The decision on which term to explain and the decided content and manner of the explanation.\n"
                "2. \"Timing\": The decision on when to provide the explanation based on 'now observation' fields 'Agent action', 'User feedback', and 'inference' field 'Personalization'.\n"
                "\n"
                "This is how you generate 'action', based on combining updated 'previous observation' generated by assistant1 and 'inference' generated by assistant2:\n"
                "1. \"Explanation\": You need to decide which term to explain and the content and manner of the explanation based on 'inference' fields 'Needs inferring', 'Interaction', 'Time spent'.\n"
                "2. \"Timing\": You need to decide the best timing to provide the explanation based on 'now observation' fields 'Agent action', 'User feedback', and 'inference' field 'Personalization'. \n"
                "\n"



                "After assistant3 has completed its decision making, assistant 4's task is next below:\n"
                "\n"

                "You are another agent for an AI research assistant, named assistant4，You need to update Agent action field of updated 'previous observation' generated by assistant1.\n"
                "The updated 'previous observation' generated by assitant1 has five fields\n"
                # "1. \"Reading part\": A coherent record of the content and section of the literature the user is reading in the current and past observations.\n"
                # "2. \"Interaction\": A coherent record of the user's interaction with the text in the current and past observations.\n"
                # "3. \"Time spent\": A coherent record of the time the user has spent on the content section in the current and past observations.\n"
                # "4. \"Agent action\": A coherent record of the agent's actions after the previous observation and all previous actions.\n"
                # "5. \"User feedback\": A coherent record of the user's feedback on the AI assistant's behavior after the previous observation and all previous feedback.\n"
                "\n"
                "As assistant4, your task is to update the Agent action field in updated 'previous observation' generated by assitant1 by using 'action' generated by assistant3.\n"

                "You can't output anything generated in assitant1, assistant2 and assistant3. You only output JSON which you generate by assistant4 as output. Complete the output task as follows:\n"
                "You can only generate JSON by using updated 'previous observation' generated by assistant4."

                "The output is completed strictly as follows:\n"
                "You must output JSON with a structure which have five memory fields same as 'previous observation'.\n"
                "You must show the entire JSON.\n"
                "You must use double quotes (\") for correct JSON format.\n"
                "You must not change the names of the default memory fields. Only update the value.\n"
                "After assistant1 completes the task(except updating Agent action), it's assistant2's turn to perform the task."
                "\n"
#####




        }
    ]

    chat_completion = openai.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=prompts,
    )

    output = chat_completion.choices[0].message.content
    return output


if __name__ == "__main__":

    # Here is an example for testing the agent per observation in the "new observation.txt"

    while True:
        # Read the input data (an array of user actions)
        with open("new_observations_0.txt", "r", encoding='utf-8') as file:
            data = json.load(file)
        n=4
        # Agent acts per input

        #for i in data:
        for i in range(n):

            # Input 1: memory
            with open("memory.json", "r") as json_file:
                prior_memory = json.load(json_file)
            prior_memory = json.dumps(prior_memory)
            print(f"\n\nPrevious memory:\n{prior_memory}\n")

            # Input 2: observation on user

            enter = input("Press enter to input the next observation.")
            observation = enter
          # observation = i

            # Agent updates the memory and decides actions
            post_memory = agent(prior_memory, observation)
            print(f"\n\nUpdated memory:\n{post_memory}\n")

            # Create a log for you to check
            with open("log.txt", "a") as text_file:
                text_file.write(post_memory + "\n")

            # Store the updated memory
            with open("memory.json", "w") as json_file:
                json_file.write(post_memory)

            # input("Press enter to input the next observation.")